### ISSUE TITLE
Greek Phi character in image metadata causes civitai to fail to process metadata

### ISSUE THREAD

**Issue by lendrick** [ljleb/sd-webui-neutral-prompt#18]
I went into the code and changed it to "phi" and the issue went away.  I'm running vladmandic, but someone also reported that it breaks automatic1111's ability to push image metadata to the text2img page.

**Comment by ljleb** [comment]
As the PR in auto1111 hasn't been updated in 2 weeks, I will introduce a fix for this. A bit annoying but when a1111 merges to main, to get old prompts to work, you will need to have this extension installed and active.
