### ISSUE TITLE
Latent Coupler + Neutral Prompt

### ISSUE THREAD

**Issue by ljleb** [ljleb/sd-webui-neutral-prompt#20]
### Discussed in https://github.com/ljleb/sd-webui-neutral-prompt/discussions/19

<div type='discussions-op-text'>

<sup>Originally posted by **Deph1** June  6, 2023</sup>
Hello! Is it plausible to use this extension alongside latent coupler? 

</div>

**Comment by ljleb** [comment]
Will look into it, possible there are some incompatibilities with other extensions at the moment. I'm working on making this work with the builtin composable lora extension #17 I'll see if I can find a common fix.

**Comment by ljleb** [comment]
@Deph1 can you share a link to the latent couple extension you are using? It seems the original repo is out of date with a1111 webui, and there are numerous forks. Should I test against this fork? https://github.com/ashen-sensored/stable-diffusion-webui-two-shot

**Comment by nerdyrodent** [comment]
Working for me*
(*interesting things can happen with negative prompts if lc is enabled and the positive prompts ends with negative weights)
