### ISSUE TITLE
`Enabled` setting is ambiguous when added to other settings panels

### ISSUE THREAD

**Issue by catboxanon** [ljleb/sd-webui-neutral-prompt#27]
https://github.com/ljleb/sd-webui-neutral-prompt/blob/ab5c46d44b0324991b4c1fb5008da3b55e9dd073/lib_neutral_prompt/ui.py#L86

The enable option isn't very clear when it's added to the `quicksettings_list` or `extra_options`. Should probably be changed to `Neutral Prompt extension enabled` or similar.

The Prompt Fusion extension actually has this same issue btw: https://github.com/ljleb/prompt-fusion-extension/blob/c8748ddc2d3c05b745a5ecfa03b1e2d4b3129a0c/scripts/promptlang.py#L23

**Comment by ljleb** [comment]
IMO this is more a problem with the quicksettings display not showing which tab it comes from. It is easier to change in the extensions so I'll rename the labels.
