### ISSUE TITLE
Constant errors like this: An unexpected noise weight was encountered at prompt

### ISSUE THREAD

**Issue by Nrgte** [ljleb/sd-webui-neutral-prompt#30]
So I'm currently not even using Neutral Prompt, but I constantly get these kinds of errors in the console:

An unexpected noise weight was encountered at prompt #0
Expected :0.4, but got :1.0
This is likely due to another extension also monkey patching the webui noise blending function

Probably related to ADetailer, but why are these popping up since I'm not using Neutral Prompt..

Thanks!

**Comment by ljleb** [comment]
These are warnings, you can safely ignore the messages when not using any feature of the extension. These are mostly useful for debugging, I'll add a checkbox to toggle verbose messages.

**Comment by Nrgte** [comment]
Okay, thanks for the headsup!

**Comment by ljleb** [comment]
Added a checkbox to not print warnings by default. Enable it if you want to tradeoff console logs clutter for feedback on accuracy of prompt tree mapping
