### ISSUE TITLE
Neutral Prompt causes a crash if the model is set to SDXL 1.0 in a1111 version 1.5.1

### ISSUE THREAD

**Issue by Nrgte** [ljleb/sd-webui-neutral-prompt#38]
It seems like the neutral prompt extension is not compatible with the new SDXL. A checkmark to disable the extension without having to disable it under the extension tab would be nice.

Thanks!

**Comment by ljleb** [comment]
There is one in the settings of the extension, as it wasn't a problem before. I will move it to the extension accordion eventually if I am unable to make the extension work with sdxl.

**Comment by ljleb** [comment]
It shouldn't crash on the last version of the extension however. Please update the extension.
