### ISSUE TITLE
`CFG rescale` only works on first generation

### ISSUE THREAD

**Issue by catboxanon** [ljleb/sd-webui-neutral-prompt#43]
Title. Upon loading the webui, the only time CFG rescale works is on the very first generation of an image. All generations that follow ignore the parameter. Using a debugger I can see it never reaches [this line](https://github.com/ljleb/sd-webui-neutral-prompt/blob/58cb0312eb0802e41f4cbfb50d21db1287c9478a/lib_neutral_prompt/cfg_denoiser_hijack.py#L58) on those subsequent generations. Not sure what the cause is.

This is with version 1.6.0 of the webui. I haven't tested with all other extensions disabled yet but I don't believe I have any that would interfere with this.

---

While you're here, I believe this also is no longer necessary in the readme. https://github.com/ljleb/sd-webui-neutral-prompt#known-issues

**Comment by ljleb** [comment]
Thanks, I'll look into it. As the code is hard patched, I don't see how this happens. Maybe it depends on the sampler?

You're right for the incompatibility. I did update the code to make it work in 1.6 and still fail in 1.5.x or earlier, overlooked the readme.

**Comment by ljleb** [comment]
Unfortunately, I'm unable to reproduce this with these extensions enabled:
- adetailer
- embedding-inspector
- prompt-fusion
- controlnet
- fabric
- neutral prompt
- surper merger
- merge board
- model toolkit
- builtin extensions

If you have any of these extensions enabled, they are probably not responsible for the bad interaction.

**Comment by ljleb** [comment]
If you use specific generation parameters that cause this, it would help me narrow it down.
