### ISSUE TITLE
X/Y/Z plot support for CFG rescale

### ISSUE THREAD

**Issue by Miczu** [ljleb/sd-webui-neutral-prompt#52]
Hi,
I was testing CFG rescale and it looks useful, but has some issues.

The as value goes up, I notice image becoming more gray (below example with 0.0, 0.5, 0.75). It looks like there is some gain in quality, so I'm trying to figure out if I can combat the gray part with CFG value or something. Alternatively I'm considering to use some CFG tweaking from https://github.com/mcmonkeyprojects/sd-dynamic-thresholding - but This is hard to do without X/Y/Z plot. 

Is this something I can request to be added? 😇
 
![01724-1_eeb82c5a](https://github.com/ljleb/sd-webui-neutral-prompt/assets/48890028/0ac79f52-a050-4966-a333-3e30e130d7b3)
![01725-1_eeb82c5a](https://github.com/ljleb/sd-webui-neutral-prompt/assets/48890028/21754520-90de-41c0-a9a8-d4f33de7463e)
![01726-1_eeb82c5a](https://github.com/ljleb/sd-webui-neutral-prompt/assets/48890028/2ad47f6a-1ef8-4b8d-a3e6-733f19678f7c)

**Comment by ljleb** [comment]
We can add an option for this, sure. CFG Rescale works best with models that were trained with offset noise. I assume your model wasn't trained with offset noise, which is why you get more washed out results. Try for example with https://huggingface.co/Xynon/SD-Silicon/blob/main/Silicon29/Silicon29-dark.safetensors

**Comment by Miczu** [comment]
Are there different types of models based on how they are trained? Is there easy way to tell them apart when browsing on civita for example?

**Comment by Miczu** [comment]
Silicon29-dark doesn't interact at all with CFG rescale, is that how it should look like?

**Comment by Miczu** [comment]
Silicon29-dark appears to handle it better, but there is still the gray effect (0, 0.75, 1.0). Probably it's fine for this one to use paper recommended 0.7 value, but most models I have don't handle it as well 😞 
![01739-1_e8910ab7](https://github.com/ljleb/sd-webui-neutral-prompt/assets/48890028/0ef4b342-be80-498b-9eee-c8f06c51372f)
![01740-1_e8910ab7](https://github.com/ljleb/sd-webui-neutral-prompt/assets/48890028/78afb5eb-1254-4a4f-bcc0-f8c13e3928c4)
![01741-1_e8910ab7](https://github.com/ljleb/sd-webui-neutral-prompt/assets/48890028/69d95b2c-e84d-4c68-9461-5d3baf9c2589)

**Comment by ljleb** [comment]
> Are there different types of models based on how they are trained? Is there easy way to tell them apart when browsing on civita for example?

AFAIK no, you have to check the details of the model. It isn't an architectural change, but a feature the model either learns

**Comment by Miczu** [comment]
No CFG rescale, Disabled FreeU
![grid-0037](https://github.com/ljleb/sd-webui-neutral-prompt/assets/48890028/b27cec02-0d78-49be-b1c8-540a5a27ca64)
0.92 Cfg Rescale, complex FreeU settings:
![grid-0037](https://github.com/ljleb/sd-webui-neutral-prompt/assets/48890028/2611fc22-c050-464a-8896-427f4e8e1e19)

I think CFG rescale with some FreeU fixes looks solid

**Comment by ljleb** [comment]
Sorry for taking so long here, I don't want to make any promises but I should get xyz grid to work soon ™️

**Comment by Miczu** [comment]
Thanks, looking forward to experimenting with it ❤️
