### ISSUE TITLE
having an issue using brackets [ ]

### ISSUE THREAD

**Issue by kenwud** [ljleb/sd-webui-neutral-prompt#53]
files attached of the pompt im trying to use, seems that when i try to follow the example of using brackers [ ] to divide sections of the prompt for use with different AND_ sections, the console throws an error message, and nothing generates, ill also attach a screenshot or text file of the log output
![image](https://github.com/ljleb/sd-webui-neutral-prompt/assets/5750041/80f2a8a2-3ed3-4f3a-b06d-6a86c092e8dd)
![image](https://github.com/ljleb/sd-webui-neutral-prompt/assets/5750041/cb493763-393a-4486-a88c-ee4b2e881934)

also, auto111 seems to automatically format the prompt in such a way that it could be causing the problem, but im not totally sure.
thanks for taking the time to read this i hope it is descriptive enough to make sense of the problem

log output:
![image](https://github.com/ljleb/sd-webui-neutral-prompt/assets/5750041/68ce00df-3d62-4cac-9ebb-6bc1b29d6323)
at the very top is a previous failed generation, then i got one to work without brackets, then the most recent output is an attempt with the above prompt

**Comment by kenwud** [comment]
update,. 
adding strengh to the tokens seems to resolve the issue 
![image](https://github.com/ljleb/sd-webui-neutral-prompt/assets/5750041/c126257b-736e-4c83-a82a-6e185e5192de)
image above 
example:
AND_SALT [token, another token] :1.2, 
works

**Comment by kenwud** [comment]
sorry to waste your time, thank you Cat with 4gb vram send help in the civitai discord for the suggestion!

**Comment by ljleb** [comment]
Well this is not the expected behavior anyways, thanks for reporting. Which extension are enabled here? Maybe it's caused by a monkey patch or prompt parsing conflict conflict.
