### ISSUE TITLE
JS error when additional quicksettings are added

### ISSUE THREAD

**Issue by obfuscode** [ljleb/sd-webui-neutral-prompt#64]
**Issue:**
It looks like Neutral Prompt isn't getting the correct selector for the txt2img or img2img Prompt field when there is _anything_ additional added to the UI that comes before the txt2img prompt field. This includes additional Quicksettings or additional primary tabs added by other extensions.

**Reproducible:** Yes

**Details:**
I did a new install of Automatic1111 through Pinokio with no additional extensions and added `sd_vae` and `pad_cond_uncond` to the default `sd_model_checkpoint` in the "Quicksettings list" setting.

I removed the quicksettings and it functioned again so I re-added my extensions that added additional primary section tabs and it broke once more.

**Hypothesis:**
However you're calculating the `id` you're passing to the `instance_map[]` is being thrown off by the addition of any parent or parent sibling elements.

![Screenshot 2024-01-31 224919](https://github.com/ljleb/sd-webui-neutral-prompt/assets/2160089/4daa76b4-b5c4-416d-87f3-53bffc2218dc)

```txt
Blocks.svelte:360 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'props')
    at Blocks.svelte:360:50
    at Array.map (<anonymous>)
    at we (Blocks.svelte:360:21)
```
```js
let payload = {
	fn_index: dep_index,
	data: dep.inputs.map((id) => instance_map[id].props.value), // Error here
	event_data: dep.collects_event_data ? event_data : null
};
```

**Comment by ljleb** [comment]
Is this a problem even after pressing F5? Usually whenever the ui has to be recreated in gradio, it's a good idea to refresh the page. Until the UI is recreated exactly the same, some component indices will be off by some value and it will break down on practically any interaction.

Can you clarify how I can reproduce this?
